- name: Start firewalld
  systemd:
    name: firewalld
    state: started

- name: Set default zone to 'public'
  ansible.builtin.command: firewall-cmd --set-default-zone=public
  register: default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'
  
- name: Allow SSH inbound connections
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: yes
    state: enabled

- name: Allow all existing connections to communicate back
  ansible.builtin.command: firewall-cmd --direct --add-rule ipv4 filter OUTPUT 0 -m state --state ESTABLISHED,RELATED -j ACCEPT 

- name: Allow outbound DNS, NTP connections and any localhost to localhost connections
  ansible.builtin.command: firewall-cmd --direct --add-rule ipv4 filter OUTPUT 1 {{ item }}
  loop:
    - "-p tcp -m tcp --dport 53 -j ACCEPT"
    - "-p udp --dport 53 -j ACCEPT"
    - "-p udp --dport 123 -j ACCEPT"
    - "-o lo -j ACCEPT"

- name: Set default to DROP all other packets
  ansible.builtin.command: firewall-cmd --direct --add-rule ipv4 filter OUTPUT 2 -j DROP

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded