- name: Install required packages
  community.general.pacman:
    name: git gcc openssh firewalld dhclient connman htop curl wget
    state: latest
    # python-firewall

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- include_tasks: rustup.yml
  when: cargo_exists is failed