- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  register: rustup_install