# tasks file for install
- name: Update repositories
  apt: 
    update_cache: yes

- name: Upgrade all apt packages
  apt: 
    upgrade: dist
    force_apt_get: yes

- name: Install tools
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - gcc
    - build-essential
    - openssh-server
    - firewalld
    # - python3-pip
    # - python3-setuptools
    # - dhclient
    # - connman
    - htop
    - curl
    - wget

# - name: Install firewalld python package
#   ansible.builtin.pip:
#     name: firewalld

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- include_tasks: rustup.yml
  when: cargo_exists is failed
  register: rustup_install

# - name: Install rustup via apt
#   when: rustup_install is failed
#   apt:
#     name: rustup
#     state: latest
